### ISSUE TITLE
Split Email Verification and Signup - Block Sign In set to Yes

### ISSUE THREAD

**Issue by danielquest** [azure-ad-b2c/samples#116]
Hi Guys,

First all this is a brilliant repository.

I was trying to do the opposite flow instead of verify the email in the first step I would like to verify the email in the last step.

The issue is when implementing that way the account is created with "Block Sign In set to Yes" so the user cannot sing in after the account is created.

Have you ever been thought this scenario?

https://github.com/azure-ad-b2c/samples/blob/master/policies/split-email-verification-and-signup

**Comment by JasSuri** [comment]
Block sign in is set up True when you try write the password in a step that is subsequent to one where it’s actually collected. Maybe this is your cause.

**Comment by danielquest** [comment]
@JasSuri I really appreciate your fast reply. Yes that is definitely my case. Do you know if there is any documentation on B2C that specifies that?

**Comment by JasSuri** [comment]
I don't think we specifically documented that.
The first problem is that the password wont actually exist in any orchestration step outside of the one where its captured. 
So when/if you write the account without the password, its marked as disabled. Then when you eventually write the password to the account, its null, if the account is being written here, then again, since password will be null, the accounts is marked disabled.

Here's what id do.
1. Sign Up form - write the account. Add an extension attribute to mark the account with unverified email (extension_emailVerified: false)
2. Present the Email verification screen, if the user succeeds, then mark the extension attribute as true (extension_emailVerified: true).

Then on Sign In journey
1. Normal sign in page, but read back the extension_emailVerified value
2. If the extension_emailVerified=false, present the email verification screen

**Comment by danielquest** [comment]
@JasSuri Thanks a lot for the insight that is very helpful.
