### ISSUE TITLE
Is it possible to have forgot username action Azure AD B2C?

### ISSUE THREAD

**Issue by anomepani** [azure-ad-b2c/samples#121]
Generating user accounts for the onboarding process is a common feature.

Instead of Email, we are using random unique alphanumeric string to generate username and use it for sign up and sign inflow.
If the user forgot his username then how he can recover his username?

Does Forgot username action Support in Azure AD B2C?
Or
Does can we add our custom action to leverage this feature?

Thanks in advance.

**Comment by JasSuri** [comment]
You can build any flow you like, the repo shows a lot of concepts.
You could build any UX, but for example:

1. User enters the email associated with their username (self asserted page with a validation technical profile that reads the user by email) 
2. User gets an OTP and verifies it (either our built in email verification or custom email sample)
3. User is sent an email with their username (rest api to fire off email) 
4. User left hanging on a page with a message on screen to check their inbox (self asserted page with paragraph claim with text)

Since this isn’t an issue with any sample, I’ll close this and better to ask for help on stackoverflow.
