### ISSUE TITLE
strongAuthenticationEmailAddress error in force-unique-email-across-social-identities 

### ISSUE THREAD

**Issue by Andrej997** [azure-ad-b2c/samples#122]
When I use the given sample and uncomment 
PersistedClaim ClaimTypeReferenceId="email" PartnerClaimType="strongAuthenticationEmailAddress" 
 in TechnicalProfile Id="AAD-UserWriteUsingAlternativeSecurityId" 
and
OrchestrationStep Order="6" Type="ClaimsExchange"
          Preconditions
            Precondition Type="ClaimsExist" ExecuteActionsIf="true"
              Value objectId Value
              Action SkipThisOrchestrationStep Action
            Precondition          
		        Precondition Type="ClaimsExist" ExecuteActionsIf="false"
              Value tempObjectId Value
              Action SkipThisOrchestrationStep Action
            Precondition
          Preconditions
          ClaimsExchanges
            ClaimsExchange Id="AAD-UserReadUsingSocialEmail-NoError" TechnicalProfileReferenceId="AAD-UserReadUsingSocialEmail-NoError" 
          ClaimsExchanges
        OrchestrationStep
portal throws an error while uploading : "Input Claim 'strongAuthenticationEmailAddress' is not supported in Azure Active Directory Provider technical profile 'AAD-UserReadUsingSocialEmail-NoError' of policy 'B2C_1A_ForceUniqueEmail_signup_signin'."

Please help.

**Comment by JasSuri** [comment]
The input claim in an AAD Technical profile is used to locate an account by a unique identifier.
The `strongAuthenticationPhoneNumber` is not a uniquely identifiable field for a user object, a more than one account can share the same phone number.
Hence the error you are getting, since its not a field constrained to uniqueness, it cannot be used to look up an account via an input claim.

What were you trying to achieve by uncommenting this section?

**Comment by Andrej997** [comment]
I've tried to restrict users to sign up with the same email address with different identity providers (i.e. same email for Google and Microsft acc). So I tried to use strongAuthenticationEmailAddress for that, but that fiels can only be accessible with Persisted or Output claim. I didn't find a way how to resolve that, so I've used other filed.

**Comment by JasSuri** [comment]
If you want to use a uniquely contrained field for the users identifier, you should use the `signInName` attribute.
Eg `signInName.myIdentifierName`
You can persist to that, and you can find a user by it.

**Comment by WilliamWatterson86** [comment]
@Andrej997 were you able to find a solution to your problem? I have the same issue where I need to restrict users from signing up with the same email on multiple social providers

**Comment by JasSuri** [comment]
When writing the social account, parse their email from the IdP (or have them provide it if not found), then before writing the account, you must do a lookup for their email by `signInName.socialEmail`. If found, you need to do something - show an error, account linking mechanism.
If not found, then write the account, and write their social email into `signInName.socialEmail`.

**Comment by WilliamWatterson86** [comment]
@JasSuri have you an example of how this would work?

**Comment by Andrej997** [comment]
@WilliamWatterson86 this is an example of finding an existing social email (I have restricted 2 different users with the same email address) i.e. gmail for google acc and microsoft acc.


        <TechnicalProfile Id="AAD-UserReadUsingSocialEmail-NoError">
          <Metadata>
            <Item Key="Operation">Read</Item>
            <Item Key="RaiseErrorIfClaimsPrincipalDoesNotExist">false</Item>
          </Metadata>
          <InputClaims>
            <InputClaim ClaimTypeReferenceId="email" PartnerClaimType="signInNames.emailAddress" Required="true" />
          </InputClaims>
          <OutputClaims>
            <OutputClaim ClaimTypeReferenceId="tempObjectId" PartnerClaimType="objectId"/>
          </OutputClaims>
          <IncludeTechnicalProfile ReferenceId="SM-AAD" />
        </TechnicalProfile>



          <OrchestrationStep Order="4" Type="ClaimsExchange">
            <Preconditions>
              <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
                <Value>objectId</Value>
                <Action>SkipThisOrchestrationStep</Action>
              </Precondition>          
              <Precondition Type="ClaimsExist" ExecuteActionsIf="false">
                <Value>tempObjectId</Value>
                <Action>SkipThisOrchestrationStep</Action>
              </Precondition>
            </Preconditions>
            <ClaimsExchanges>
              <ClaimsExchange Id="AAD-UserReadUsingSocialEmail-NoError" TechnicalProfileReferenceId="AAD-UserReadUsingSocialEmail-NoError" />
            </ClaimsExchanges>
          </OrchestrationStep>

**Comment by JasSuri** [comment]
Just know that if you initialize the account with a social idp, and put their email in the `signInNames.EmailAddress` field, they will also have a "Local Account" with the same email, but no password attached to it. That's because the Local Account sign in/up tries to find an account via `signInNames.EmailAddress`. So if they try to sign up with the same email as the social idp, itll say account exists. That might confuse people.

So it depends if you want that behavior or not. If not, you can store the social email in something else like `signInNames.SocialEmailAddress`.

In the latter approach, you essentially do an account link process, if the account exists (lookup generically by `signInNames`), force the user to link it using whatever IdP is available on that account to prove that you own the account. Then write the email to the appropiate field (Local/Social). This is the smartest solution in my opinion.
