### ISSUE TITLE
Correlation Failed with invite sample

### ISSUE THREAD

**Issue by hisuwh** [azure-ad-b2c/samples#13]
I'm trying to implement the email invitation sample here:
https://github.com/azure-ad-b2c/samples/tree/master/policies/invite

I am able to get to the custom sign-up page successfully and it validates the token through my endpoint.  But once I have signed up and it redirects back to my application I get a "Correlation Failed" error message.

I don't actually need to send the user an email as we have a process for that already.  So I have also tried doing a normal challenge and manually setting the id_token_hint in the OnRedirectToIdentityProvider event.

Again I am able to get the custom sign up page and sign up.  However I then get this error when it redirects back to my application:

`IDX10501: Signature validation failed. Unable to match keys: kid: '[PII is hidden]', token: '[PII is hidden]'`

I would prefer to use the latter solution but any help getting either to work would be appreciated

**Comment by JasSuri** [comment]
If the B2C page loads when using Id_token_hint, and Id_token_hint is extracted in step 1 of the journey, then the issue is not to do with the Id_token_hint usage. Seems more like the well known open id endpoint (authority) set in the App is incorrectly setup, so the App is not finding the public key at the OIDC metadata with the Key ID specified in the token that it received from B2C.
You may want to configure your app with a Built In policy first to isolate this issue.
