### ISSUE TITLE
The username or password provided in the request are invalid.

### ISSUE THREAD

**Issue by zhouzhou1102** [azure-ad-b2c/samples#151]
![Untitled](https://user-images.githubusercontent.com/38065901/102291035-2b9b6c00-3f7d-11eb-8b50-9dfba93b3170.png)

The user or administrator has not consented to use the application with ID '{identifier}'{namePhrase}. Send an interactive authorization request for this user and resource.

Sign in:Encountered the above problems, do not know where the configuration problems
Sign up:success
reset Password:success

**Comment by JasSuri** [comment]
You’re better off automating then setup with this tool: https://aka.ms/iefsetup. 

Make sure to delete your identityExperienceFramework and proxyIdentityExperienceFramework Application registrations before running the tool.

The root cause is you have not given admin consent as per the doc at https://aka.ms/ief.

> Now, grant permissions to the API scope you exposed earlier in the IdentityExperienceFramework registration:
In the left menu, under Manage, select API permissions.
Under Configured permissions, select Add a permission.
Select the My APIs tab, then select the IdentityExperienceFramework application.
Under Permission, select the user_impersonation scope that you defined earlier.
Select Add permissions. As directed, wait a few minutes before proceeding to the next step.
Select Grant admin consent for (your tenant name).
