### ISSUE TITLE
Auto Signin after Signing up using invitation signup policy.

### ISSUE THREAD

**Issue by moizzaveri** [azure-ad-b2c/samples#246]
Currently I am using a invite by email custom policy. The user uses the signup link to register to our website but after signing up the user is redirected to our website and since the next page is protected goes towards the signin user flow. Is there anyway to auto signin after this signup flow? Because normally in signup userflows users are directly logged in and does not require to go through one more extra step.

**Comment by JasSuri** [comment]
You need to use id_token_hint via your application, and not send the direct "run now" link to the user.

SPA: https://docs.microsoft.com/en-us/azure/active-directory-b2c/enable-authentication-spa-app-options#pass-id-token-hint

.NET: https://docs.microsoft.com/en-us/azure/active-directory-b2c/enable-authentication-web-application-options#pass-id-token-hint

Since this is not a bug with the sample, follow up on stackoverflow.
