### ISSUE TITLE
B2C-Token-Includes-AzureAD-BearerToken, User Journey Issue

### ISSUE THREAD

**Issue by W4775** [azure-ad-b2c/samples#325]
Setup B2C with this policy:
https://github.com/azure-ad-b2c/samples/tree/master/policies/B2C-Token-Includes-AzureAD-BearerToken

Policy authenticates but end up throwing this error (captured by AppInsights)
Exception Message: The user journey 'SignUpOrSignInUsingAzureAD_issueAADtoken' does not specify first step or the first step is not a claims exchange.

All XML is stock from the repo outside of updating the tenant ID and App ID's where applicable.

**Comment by astaykov** [comment]
Hi @W4775, please make sure that you are using correct values for the following parameters in the `metadata` section of your `Azure AD` identity provider:

```xml
         <Metadata>
            <!-- omitted for clarity -->
            <!-- TODO update client_id and IdTokenAudience to match your configuration-->
            <!-- <Item Key="client_id">6de4c9fd-c266-4b04-a0fa-782e9654da71</Item> -->
            <!-- <Item Key="IdTokenAudience">6de4c9fd-c266-4b04-a0fa-782e9654da71</Item> -->

            <!-- !! very important !! -->
            <Item Key="UsePolicyInRedirectUri">false</Item>
            <!-- omitted for clarity -->
          </Metadata>
          <CryptographicKeys>
            <!-- TODO update StorageRefenceId to match your configuration-->
            <Key Id="client_secret" StorageReferenceId="B2C_1A_TenantApplicationKey"/>
          </CryptographicKeys>
```

The values of `client_id` (resp. `IdtokenAudience`) and `B2C_1A_TenantApplicationKey` **must** represent an app registration in your *corporate* Azure AD tenant, and **not** your B2C tenant!

Because, this sample uses the `/common` endpoint in Azure AD, please refer to the official documentation about[ integrating Azure AD Common endpoint as Identity provider](https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-azure-ad-multi-tenant?pivots=b2c-custom-policy#register-an-azure-ad-app) first.
